### ISSUE TITLE
Questions About Training the Marigold Model and Downsampling the Input

### ISSUE THREAD

**Issue by Selena1105** [Beerend/NeRF-OR#1]
Hi,

Thank you for sharing this great project! I have a couple of questions regarding your implementation of the NeRF-OR model:

1. Did you train the Marigold model from scratch, or did you use the pre-trained weights provided by the developers?
2. I noticed that you perform downsampling on the input images. Could you share the reasoning behind this step and clarify the method you used for downsampling (e.g., average pooling, max pooling, or something else)?

Looking forward to your insights! Thank you for your time.

**Comment by Beerend** [comment]
Thank you for the interest in the project! Regarding your questions:

1. We used Marigold with its pre-trained weights. We were suprised with how well it works out-of-the-box!
2. Downsampling was performed to mitigate the large memory requirements when loading data on the GPU. We experimented with larger input images, but we didn't see large improvements.

I hope that answers your questions!

**Comment by Selena1105** [comment]
Thank you very much for your answer!
